package com.design.umlviewer.domain.dossier;

import com.design.umlviewer.domain.model.ArchitectureGraph;
import com.design.umlviewer.domain.model.ClassNode;
import com.design.umlviewer.domain.model.ComponentNode;
import com.design.umlviewer.domain.model.DependencyEdge;
import com.design.umlviewer.domain.policy.ArchitecturePolicy;
import jakarta.enterprise.context.ApplicationScoped;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@ApplicationScoped
public class ArchitecturalDossierGenerator {

  private static final List<String> DEFAULT_TIER_NAMES =
      List.of("Domain Core (L0)", "Application (L1)", "Adapters (L2)", "Infrastructure (L3)");

  public String generate(ArchitectureGraph graph, ArchitecturePolicy policy) {
    if (graph == null) {
      return "# Clean Architecture Optimization Dossier\n\nNo architecture graph available.\n";
    }

    StringBuilder sb = new StringBuilder();
    String title =
        (graph.title() != null && !graph.title().isBlank())
            ? graph.title()
            : (policy != null && policy.title() != null ? policy.title() : "Workspace");

    sb.append("# Clean Architecture Optimization Dossier — ").append(title).append("\n\n");
    sb.append("Generated by **Archlens Dynamic Clean Architecture Workbench**.\n");
    sb.append(
        "This dossier identifies architectural ring boundaries, illegal outward dependency rule violations,\n");
    sb.append(
        "and concrete Dependency Inversion Principle (DIP) refactoring guidance for Large Language Models.\n\n");
    sb.append("---\n\n");

    // 1. Concentric Tiers
    sb.append("## 1. Clean Architecture Concentric Rings\n\n");
    sb.append("| Tier | Level | Packages |\n");
    sb.append("| :--- | :---: | :--- |\n");

    List<List<String>> levels =
        (policy != null && policy.levels() != null) ? policy.levels() : List.of();

    for (int i = 0; i < Math.max(levels.size(), 4); i++) {
      String tierName =
          (i < DEFAULT_TIER_NAMES.size()) ? DEFAULT_TIER_NAMES.get(i) : "Ring Level " + i;
      List<String> pkgs = (i < levels.size()) ? levels.get(i) : List.of();
      String pkgList = pkgs.isEmpty() ? "*(none declared)*" : "`" + String.join("`, `", pkgs) + "`";
      sb.append("| **")
          .append(tierName)
          .append("** | Level ")
          .append(i)
          .append(" | ")
          .append(pkgList)
          .append(" |\n");
    }
    sb.append("\n---\n\n");

    // Index all classes for fast metadata lookup
    Map<String, ClassNode> classMap = new HashMap<>();
    if (graph.components() != null) {
      for (ComponentNode comp : graph.components()) {
        if (comp.classes() != null) {
          for (ClassNode cls : comp.classes()) {
            classMap.put(cls.id(), cls);
            classMap.put(cls.name(), cls);
          }
        }
      }
    }
    if (graph.unassigned() != null) {
      for (ClassNode cls : graph.unassigned()) {
        classMap.put(cls.id(), cls);
        classMap.put(cls.name(), cls);
      }
    }

    // 2. Diagnostics Summary
    List<DependencyEdge> allEdges = graph.edges() != null ? graph.edges() : List.of();
    List<DependencyEdge> violations = new ArrayList<>();
    for (DependencyEdge edge : allEdges) {
      if (edge.isViolating()) {
        violations.add(edge);
      }
    }

    int componentCount = graph.components() != null ? graph.components().size() : 0;
    int classCount = classMap.size();
    int edgeCount = allEdges.size();

    sb.append("## 2. Architectural Diagnostics Summary\n\n");
    sb.append("- **Total Components (Packages)**: ").append(componentCount).append("\n");
    sb.append("- **Total Classes / Types**: ").append(classCount).append("\n");
    sb.append("- **Total Dependency Edges**: ").append(edgeCount).append("\n");

    if (violations.isEmpty()) {
      sb.append(
          "- **Clean Architecture Status**: ✅ **Conforming** (Zero outward dependency rule violations detected)\n\n");
    } else {
      sb.append("- **Clean Architecture Status**: 🚨 **")
          .append(violations.size())
          .append(" Dependency Rule Violation")
          .append(violations.size() == 1 ? "" : "s")
          .append(" Detected**\n\n");
    }
    sb.append("---\n\n");

    // 3. Violations Breakdown & DIP Guidance
    sb.append("## 3. Prioritized Architectural Violations & DIP Refactoring Prescriptions\n\n");

    if (violations.isEmpty()) {
      sb.append(
          "🎉 **No dependency violations found.** All source code dependencies adhere to Uncle Bob's Dependency Rule,\n");
      sb.append("pointing strictly inward toward higher-level domain policies.\n\n");
    } else {
      for (int i = 0; i < violations.size(); i++) {
        DependencyEdge v = violations.get(i);
        ClassNode fromCls = classMap.get(v.from());
        ClassNode toCls = classMap.get(v.to());

        String fromLocation =
            fromCls != null && fromCls.filePath() != null ? fromCls.filePath() : v.from();
        String toLocation = toCls != null && toCls.filePath() != null ? toCls.filePath() : v.to();

        String fromTier = resolveTierName(fromCls != null ? fromCls.level() : null);
        String toTier = resolveTierName(toCls != null ? toCls.level() : null);

        String portName = proposePortName(v.to());

        sb.append("### Violation ")
            .append(i + 1)
            .append(": `")
            .append(v.from())
            .append("` ➔ `")
            .append(v.to())
            .append("`\n\n");
        sb.append("- **Direction**: `")
            .append(fromTier)
            .append("` depends on `")
            .append(toTier)
            .append("`\n");
        sb.append(
            "- **Uncle Bob's Law**: Source code dependencies must point ONLY inward, toward higher-level policies.\n");
        sb.append("- **Source File**: `").append(fromLocation).append("`\n");
        sb.append("- **Target File**: `").append(toLocation).append("`\n");
        sb.append("- **Prescribed Dependency Inversion Principle (DIP) Fix**:\n");
        sb.append("  1. Define an interface port `")
            .append(portName)
            .append("` in the inner layer (`")
            .append(fromTier)
            .append("`).\n");
        sb.append("  2. Change `")
            .append(simpleName(v.from()))
            .append("` to declare dependencies exclusively against `")
            .append(portName)
            .append("`.\n");
        sb.append("  3. Make the outer concrete class `")
            .append(simpleName(v.to()))
            .append("` implement `")
            .append(portName)
            .append("`.\n");
        sb.append(
            "  4. Wire the concrete implementation at the infrastructure boundary using dependency injection.\n\n");
      }
    }
    sb.append("---\n\n");

    // 4. Actionable LLM Instructions
    sb.append("## 4. Actionable LLM Refactoring Instructions\n\n");
    sb.append("```markdown\n");
    sb.append(
        "You are an expert Clean Architecture software engineer and refactoring specialist.\n\n");
    sb.append("TASK:\n");
    if (violations.isEmpty()) {
      sb.append("The current codebase cleanly conforms to Clean Architecture boundaries.\n");
      sb.append("Ensure any future enhancements maintain strict inward dependency flow.\n");
    } else {
      sb.append("Refactor the codebase to eliminate the ")
          .append(violations.size())
          .append(" architectural violation")
          .append(violations.size() == 1 ? "" : "s")
          .append(" detailed above.\n\n");
      sb.append("EXECUTION PRINCIPLES:\n");
      sb.append(
          "1. Invert outward dependencies by creating interface ports in the inner layers and implementing them in the outer layers.\n");
      sb.append(
          "2. Maintain strict separation of concerns across concentric rings (Domain -> Application -> Adapters -> Infrastructure).\n");
      sb.append(
          "3. Avoid mock-heavy tests or test smells. Verify the refactoring with clean unit tests adhering to Robert C. Martin craftsmanship.\n");
      sb.append("4. Keep public contracts stable and regression-free.\n");
    }
    sb.append("```\n");

    return sb.toString();
  }

  private String resolveTierName(Integer level) {
    if (level == null) return "Unknown Layer";
    if (level >= 0 && level < DEFAULT_TIER_NAMES.size()) {
      return DEFAULT_TIER_NAMES.get(level);
    }
    return "Level " + level;
  }

  private String simpleName(String id) {
    if (id == null) return "Unknown";
    int lastDot = id.lastIndexOf('.');
    return lastDot >= 0 ? id.substring(lastDot + 1) : id;
  }

  private String proposePortName(String targetId) {
    String name = simpleName(targetId);
    if (name.endsWith("Repository")
        || name.endsWith("Client")
        || name.endsWith("Gateway")
        || name.endsWith("Service")) {
      return name + "Port";
    }
    return name + "Port";
  }
}
