quarkus.application.name=uml-viewer
quarkus.http.port=8088
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Container Image Configuration
quarkus.container-image.name=unclebob-design
quarkus.container-image.group=${IMAGE_GROUP:fmatar}
quarkus.container-image.registry=${REGISTRY:ghcr.io}
quarkus.container-image.tag=${IMAGE_TAG:latest}
quarkus.container-image.build=${BUILD_CONTAINER:false}
quarkus.container-image.push=${PUSH_CONTAINER:false}
